### ISSUE TITLE
Double Check Word of Tom GDoc

### ISSUE THREAD

**Issue by msprijatelj** [aritsune/lancer-faq#94]
It was recently mentioned in the #comp-con channel on PilotNet discord that there was a Word of Tom GDoc that had some clarifications that never made it into the Lancer FAQ website. The inciting question was “can you use the GMS integrated weapon core bonus to mount a superheavy mount” (answer: no), but there were others not mentioned too (like how Volley Module and Ravager Turret interact with each other). 

If possible, it would be helpful if the doc could be double-checked against the existing FAQ in this repo for any clarifications that could be appended to the Lancer FAQ website. Link to the doc [here](https://docs.google.com/document/d/1EqZ4SB1oigxEIgsgVDrTBarN_-TXIxM8doMPCvBAuNM/edit).

**Comment by lenaleciel** [comment]
I'll deal with it soon.

**Comment by lenaleciel** [comment]
https://github.com/aritsune/lancer-faq/pull/95
There, should be all of it, aside from a few things that were already explicit from the text.
